### ISSUE TITLE
Reduce the amount of queries

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#11]
Each second, there seem to run about 6 queries to ThingsDB (even when only the editor is open). Can we review the queries and maybe reduce/reschedule the amount of queries?

**Comment by joente** [comment]
As a solution a "refresh" button next to the collections, users etc could solve the problem.  This way  we do not have to pull them constantly. (like FireBase and Oversight for example, see screenshot from firebase)
![image](https://user-images.githubusercontent.com/6572730/76700838-cd72ed00-66bb-11ea-99cc-db9007ef4789.png)

The same for the node counters. A refresh button solves the issue of constant polling. Especially for the counters, it is actually important that the ThingsGUI by itself is not responsible for the load with the queries. Otherwise you are monitoring yourself, and not the app or whatever you want to check.

For the node streams, they are useful to poll, but only when the stream dialog is open. It is not a problem if, as a user, you have to wait a second before the lines between the nodes are visible.

The node status is actually the only information where up-to-date status is useful, but even here it is only useful if you are actually doing something with the nodes. A "switch" button to enable "Real time status" could solve the problem so polling will only be enabled when the switch is turned on. 

I think that eventually we can prevent all the polling queries and this would really be a big improvement because the tool should not have impact on ThingsDB. (except when really being used)

**Comment by AnjaBruls** [comment]
Implemented in release v0.0.6-beta
