### ISSUE TITLE
Show type relations

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#113]
It would be nice to see type relations in a type view. 

![image](https://user-images.githubusercontent.com/6572730/113669520-30169c80-96b4-11eb-9a46-5f8a053bded0.png)

For example, `bb` of type `{B}` (on type `A`) has a relation with property `aa` on type `B`. Maybe add a relation column and show something like `--> "aa" on "B" as "{A}"` ? (where B and A are again clickable)

See https://docs.thingsdb.net/v0/collection-api/mod_type/rel/ for relation documentation and https://docs.thingsdb.net/v0/collection-api/type_info/#example for an example what `type_info(..)` shows for relation information.

**Comment by AnjaBruls** [comment]
Updated in release v0.4.0
