### ISSUE TITLE
Send keep alive to prevent connection drop

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#13]
Now the tool is not polling anymore, no packages are send to keep the connection open. Socket connections will close automatically after X seconds if no traffic is generated. 

To keep the connection open, ThingsDB has the PING / PONG protocol available. The client should send each 30 or 40 seconds a PING request and ThingsDB will answer this request with PONG. This ensures the connection stays open with no other side-effects.

**Comment by AnjaBruls** [comment]
Implemented in release v0.0.7-beta.
