### ISSUE TITLE
Format start counter

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#147]
Maybe show the `started_at` property as: "Counters started at:"? I think that "started counted at:" is not correct. 

Is it possible to format the start time stamp as a date/time string in the gui?

![image](https://user-images.githubusercontent.com/6572730/132698879-adad76bd-e922-40f2-8f79-2a71ed230a57.png)

**Comment by AnjaBruls** [comment]
Changed in release v1.1.0
