### ISSUE TITLE
Cannot run procedure

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#16]
When creating a procedure for a collection, if appears as expected in the procedures list. However, when pressing run, the following error occurs:

![image](https://user-images.githubusercontent.com/6572730/77296600-4390d880-6ce8-11ea-825b-296ffc6c2173.png)

This is the procedure:
```
new_procedure('set_x', |x| .x = x);
```

**Comment by AnjaBruls** [comment]
Solved in release v0.0.7-beta
