### ISSUE TITLE
Remove timers

### ISSUE THREAD

**Issue by AnjaBruls** [thingsdb/ThingsGUI#160]
Remove timer components from ThingsGUI. The ThingsDB timer component is being revised.

**Comment by joente** [comment]
Update for syntax highlighting:

* Added `task` function.
* Added `tasks` function.
* Added `is_task` function.
* Added `again_in` function.
* Added `again_at` function.
* Added `cancel` function.
* Added `closure` function.
* Added `set_closure` function.
* Added `args` function.
* Added `set_args` function.
* Added `owner` function.
* Added `set_owner` function.
* Removed `del_timer` function.
* Removed `has_timer` function.
* Removed `new_timer` function.
* Removed `set_timer_args` function.
* Removed `timer_args` function.
* Removed `timer_info` function.
* Removed `timers_inf` function.

**Comment by AnjaBruls** [comment]
Removed in release v1.1.0
