### ISSUE TITLE
Explicit set deep

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#175]
ThingsDB will be configurable for setting the default `deep` value on every scope.
It is therefore required to be explicit for all queries where a *thing* is queried, to specify the deep level.

For example:

```
{nodes: nodes_info(), connectedNode: node_info()};
```

should be: (as function call to be compatible, should later be changed to a statement)

```
return ({nodes: nodes_info(), connectedNode: node_info()}, 1); 
```

Or, as you have full control over the query, do not return a thing but a list instead: 
```
[nodes_info(), node_info()];
```

**Comment by AnjaBruls** [comment]
Changed in v1.1.4.
