### ISSUE TITLE
focus on first input when adding propperty when creating a type

### ISSUE THREAD

**Issue by timoj** [thingsdb/ThingsGUI#210]
<img width="888" alt="Screenshot 2022-06-27 at 16 13 10" src="https://user-images.githubusercontent.com/394941/175962141-c173647a-df32-497c-977c-879c5fcbf906.png">

When adding a type, when you add an extra propperty, the focus is set to the type field. For UX it would be best to set the focus to the first input, which would be the `name` field

**Comment by AnjaBruls** [comment]
Fixed in v1.2.0
