### ISSUE TITLE
Changes to vis

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#217]
It is possible to have two arrows between types both with a multiple relation and/or multiple properties. If this is the case we should draw only a single line. 

The line _text_ should only contain the related properties.

Relation example (multiple can be separated with comma and new-line `,\n`): 
```
relation check<->users on Check as {User}
```
The `other` relation line would in this case show:
```
relation users<->check on User as Check?
```

Property example (multiple can be separated with new-lines): 
```
property check on User as Check?
```

When hover a Type, we should show all its properties. Example:

```
User (Type)
name: str<3:25>,
check: Check?
```

Another example:
```
_User (Wrap-only Type)
name: str<3:25>
```

**Comment by AnjaBruls** [comment]
To make is more visible, maybe it would be better to place the vis-network as a separate container in the collection page. Now it is  a bit hidden under the Collection info container.

**Comment by AnjaBruls** [comment]
Changed in v1.2.1.
