### ISSUE TITLE
Line in visualization is missing

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#218]
A line between two types is missing. I do not understand why exactly since most lines are drawn.

In this example below, there is a property `options` as `[WidgetOption]` on `_View` but the arrow is missing. (missing arrow is drawn in red)
![image](https://user-images.githubusercontent.com/6572730/176675977-44cb1365-66bd-4cd8-adc5-144eb7bf88c8.png)

**Comment by AnjaBruls** [comment]
Changed in v1.2.1.
