### ISSUE TITLE
Landing page after sign in

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#22]
It would be nice to have a "langing page" which is visible after a sign in to the ThingsGUI.

We should be able to go back to the landing page when cliking on the "ThingsDB" logo in the upper left of the screen.

Ideas for the page:

- [ ] Pie chart showing the total number of stored things, where each color in the chart represents a collection with the number of things stored in that specific collection.
- [ ] Version number of the ThingsGUI ?
- [ ] ?

**Comment by AnjaBruls** [comment]
Added in #23  & release v0.1.1
