### ISSUE TITLE
Syntax highlighting for new function

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#234]
The next release of ThingsDB will include new functions: 

- _arr_or_set_.map_id()
- _arr_or_set_.map_wrap(..)
- _arr_.map_type(..)

The return() and if() functions will be removed as they are replaced with statements

See branch/pull request: https://github.com/thingsdb/ThingsDB/pull/299/files

**Comment by AnjaBruls** [comment]
Added in release v1.2.2.
