### ISSUE TITLE
Minor highlight issues

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#235]
The ThingsGUI has a few minor highlight issues:

A regex accepts multiple flags: (_i_, _m_ and _s_) but they are not colored as expected, example: (only the _i_ flag is recognized) 

```
/text.*/ims;
```

When escaping a curly bracket in a template string, the content is still shown as code and not as normal string:

```
`example with {{ curlies }} in a template string`;
```

Strings are actually multi-line by default but not highlighted as such:

```
"
multi-line string
";
```

> Note that the vscode syntax highlighting has the same issues (https://github.com/thingsdb/vscode-thingsdb/issues/2)

**Comment by AnjaBruls** [comment]
Fixed in release v1.2.2
