### ISSUE TITLE
Add `ren(..)`, `fill(..)`, `enum_map(..)` and `nse(..)` functions to syntax

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#236]
Add the _thing_`.ren(..)` function. see https://docs.thingsdb.net/v1/data-types/thing/ren/
Add the _thing_`.fill(..)` function. see https://docs.thingsdb.net/v1/data-types/list/fill/
Add the `enum_map(..)` function. see https://docs.thingsdb.net/v1/collection-api/enum_map/
Add the `nse(..)` function. see https://docs.thingsdb.net/v1/collection-api/nse/

**Comment by AnjaBruls** [comment]
Added in release v1.2.2
