### ISSUE TITLE
Authentication mask `USER`

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#237]
ThingsDB has a new authentication mask (`USER`) for the combination `RUN|JOIN|CHANGE|QUERY`.
The GUI most likely needs to translate `USER` to the corresponding flags.

Example:
```json
{
    "access": [
        {
            "privileges": "USER",
            "scope": "@collection:junk"
        }
    ]
}
```

**Comment by AnjaBruls** [comment]
Fixed in release v1.2.2.
