### ISSUE TITLE
Stream graph keeps loading

### ISSUE THREAD

**Issue by timoj** [thingsdb/ThingsGUI#238]
In a 1 node setup, the stream graph keeps loading:

<img width="1024" alt="Screenshot 2022-10-26 at 13 58 03" src="https://user-images.githubusercontent.com/394941/198020271-7ba7b90a-a990-4771-aebc-e0f343506647.png">

Best response would be a message explaining why it cannot be loaded, or disabling the stream graph button when there is just 1 node

**Comment by AnjaBruls** [comment]
Fixed in release v1.2.2.
