### ISSUE TITLE
Show the exception thrown by ThingsDB

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#25]
When an error is raised by thingsdb, is it possible to show in the error message which exception is raised?

Ideal would the name of the exception and a link to the documentation, for example:

 [lookup_err](https://docs.thingsdb.net/v0/errors/lookup_err/)

**Comment by joente** [comment]
Mayby it's easy to show the error function: `overflow_err()` or `err(-100)` for a custom error

**Comment by AnjaBruls** [comment]
The error code is added to the error message like: `(-59) integer overflow` . This feature will be released in v0.1.3.

**Comment by AnjaBruls** [comment]
Implemented in release v0.1.3
