### ISSUE TITLE
Show `wse` status for procedures

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#26]
The `wse` status of procedures is an important property since it shows to the user if a certain procedure creates an event (or not).

Procedures without an event are always "save" to run since they cannot make any change to the database. 

Is it possible to make a difference between procedures with `wse` `true`/`false` inside the GUI? Maybe with an icon or color or text?

If the `wse` property would be visible a user could quickly identify all the procedures which might change the database.

**Comment by AnjaBruls** [comment]
The procedure that have side effect will have an yellow color instead of the default blue. Also within the Run, Edit and View dialog windows a line is added indicating `Note: this procedure generates an event.`. This feature will be released in v0.1.3.

**Comment by AnjaBruls** [comment]
Implemented in release v0.1.3
