### ISSUE TITLE
Add new math functions for syntax highlighting

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#266]
The following constants are added: `INT_MIN`, `INT_MAX`, `MATH_E` and `MATH_PI` _(not sure if constants are recognized by the ThingsGui)_

The following functions are added:
- abs()
- ceil()
- cos()
- exp()
- floor()
- log10()
- log2()
- loge()
- pow()
- round()
- sin()
- sqrt()
- tan()

**Comment by AnjaBruls** [comment]
Added in release v1.3.3
