### ISSUE TITLE
Backup bugs

### ISSUE THREAD

**Issue by AnjaBruls** [thingsdb/ThingsGUI#267]
- [x] **Add back up**: following error is returned when no time is set:
![image](https://github.com/thingsdb/ThingsGUI/assets/39908703/86d989cc-b4a7-4ace-ad8a-b27246198e71)
This is caused because `now()` is used and returns a float.

- [x] Opening backup info also results in an error.
![image](https://github.com/thingsdb/ThingsGUI/assets/39908703/127fa22e-24ee-4d03-a470-ae299fb7542a)
It seems to be caused by following code: 
`{ky: 'next_run', label: 'Next run at (UTC)', fn: (t) => t.slice(-1) === 'Z' ? t.slice(0, -1) : t},`

**Comment by joente** [comment]
Can you also check this for `new_token(..)` ? This method used to accept a float for the end time but while this still works in recent versions, it is marked as deprecated since long.
