### ISSUE TITLE
Unexpected behaviour Refresh button

### ISSUE THREAD

**Issue by ivomans** [thingsdb/ThingsGUI#273]
When pressing the refresh button in the 'Things Tree' window the data is not refreshed, but another page will show up, as shown in attached video.

https://github.com/thingsdb/ThingsGUI/assets/1486556/9140c22e-55b1-4015-9842-71c59777a4dd

**Comment by AnjaBruls** [comment]
Thanks for submitting this issue! This problem should be solved in upcoming release.

**Comment by AnjaBruls** [comment]
Release v1.3.3 is out now!
