### ISSUE TITLE
Search/filter in procedures and types

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#28]
When having a lot of procedures, for example in DutyCalls we have over 100 procedures, it gets difficult to navigate the procedures list.

Is it possible to add a search box in both the procedures and types to quickly filter the list?

![image](https://user-images.githubusercontent.com/6572730/80837086-6b802f80-8bf6-11ea-9851-d7df8b5d6e49.png)

**Comment by joente** [comment]
As an addition to this issue, is it possible to order the procedures and types alphabetically? This too would help to navigate.

**Comment by AnjaBruls** [comment]
This feature will be released in v0.1.3.

**Comment by AnjaBruls** [comment]
Implemented in release v0.1.3
