### ISSUE TITLE
Quick view of procedure and type

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#29]
Is it possible to add a "view" of a procedure and a type? Quite often I want to review what exactly a procedure is doing or what fields exist in a type, so a quick view would be helpful.
I explicitly like a view, so you do not have to worry about accidentally changing anything to either the procedure or type.
Both are at least easy when working with the editor.

Do not worry about showing the code of the procedure on a single line. I will make a change to ThingsDB so procedures will automatically output with line-breaks and indentation etc.

**Comment by joente** [comment]
ThingsDB version `0.8.10-alpha-0` displays procedure definitions using line-breaks and indentation which makes them readable to the user.

**Comment by AnjaBruls** [comment]
I added an extra dialog for viewing the procedures and types. This feature will be released in v0.1.3.

**Comment by AnjaBruls** [comment]
Implemented in release v0.1.3
