### ISSUE TITLE
Name of window

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#30]
The name of the browser window is currently "ThingsDB".

It would be better to change the name to for example: "ThingsGUI - localhost:9200", where `localhost:9200` is the node you are currently connected to. The name can be just plain "ThingsGUI" as long as you are not connected to any node.

**Comment by AnjaBruls** [comment]
This feature will be released in v0.1.3.

**Comment by AnjaBruls** [comment]
Implemented in release v0.1.3
