### ISSUE TITLE
Create a restore option in the GUI

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#59]
Implement a restore option in ThingsDB GUI.

When opening the restore model, the following should be done:

1. As a user you should be able to enter a filename and enable/disable a `take_access` option. 
2. When a filename is entered and the restore button is pressed, the following should be done:
3. Check with `nodes_info()` if there is more than one node and if so, check if all nodes have the latest event ID stored on disk. (stored_event_id must be equal to committed_event_id on all nodes)
4. Check if all nodes have status `READY`
5. As long as the checks above are not ok, a message should appear like: `Waiting for node x ...` and every 5 or 10 seconds the gui can ask an update with nodes_info()
6. When the checks are fine, the gui should perform the `restore(...);` command
- If successful, a model should appear with a message and a button which cannot be closed and when pressed will forward to the login page. (a new login is required after a successful restore)
- If failed, the GUI should display the error message of ThingsDB. (this may be that for example the given file does not exist)

**Comment by AnjaBruls** [comment]
Added in Release v0.2.5
