### ISSUE TITLE
Implement new backup options in GUI

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#60]
See issue https://github.com/thingsdb/ThingsDB/issues/71

- [ ] Implement an option to *delete_files* related to a backup when deleting a backup. (defaults to `false`)
- [ ] Accept a fourth optional argument when creating a scheduled backup to set the maximum number of files. (defaults to `7`)
- [ ] Extend GUI with extra backup information like the `max_files` property and `files` list

**Comment by AnjaBruls** [comment]
Added in Release v0.2.5
