### ISSUE TITLE
Add and rename ThingsDB functions

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#72]
ThingsDB has some functions which are renamed, and there are some new functions which should be updated in the language.
See: https://github.com/thingsdb/ThingsDB/issues/93 and https://github.com/thingsdb/ThingsDB/issues/89

The old function names like `iserr` etc. should be removed from the language, so user will less likely use these old functions names.

**Comment by joente** [comment]
See also thingsdb/ThingsDB#100 (new `is_closure` function)

**Comment by AnjaBruls** [comment]
Added in release v0.2.9
