### ISSUE TITLE
Add `largest_result_size` counter

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#74]
ThingsDB has a `largest_result_size` counter which represents a value in `bytes`.
If possible, it would be nice to see this value in bytes, and if > 1KiB, together with an approximate value:

Examples:

`3123123 (~3 MiB)`  ( = 2.97.. MiB, rouded gives approximately 3 MiB)
`23123 (~23 KiB)`
`117 bytes`

**Comment by AnjaBruls** [comment]
Added in release v0.2.9
