### ISSUE TITLE
Add `result_size_limit` as node information

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#75]
ThingsDB has `result_size_limit` as a new node info value.

It would be nice to see this value with an approximate value behind.

for example:

`20971520 (~20 MiB)`  (here, it is actually exact 20 MiB, but I don't think showing `~` is a problem)
`10000000 (~10 MiB)`  
`250000 (~244 KiB)`

**Comment by AnjaBruls** [comment]
Added in release v0.2.9
