### ISSUE TITLE
Change wrap-only button in view mode

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#76]
When viewing a type, the GUI shows wrap-only mode as a button which "looks" clickable:

![image](https://user-images.githubusercontent.com/6572730/96727536-705aba80-13b3-11eb-8f17-305d0a3ee988.png)

I think it would be nicer if the GUI just showed the text: `Wrap-only mode: disabled` (or `enabled`)

**Comment by AnjaBruls** [comment]
Changed in release v0.2.9
