### ISSUE TITLE
Auto select TLS when typing https:// and auto disable when typing http://

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#82]
Suggestion from @Bram:

When entering an address starting with `https://`, the GUI could auto-enable TLS since most likely this needs to be turned on.

And when starting with `http://`, it should be turned of.

To prevent unwanted behavior, the GUI could perform the enable/disable action when "leaving" the address input box.

**Comment by joente** [comment]
As a user you should still be able to enable or disable the TLS setting when using an address or host name. With the new version this is not possible anymore. I think the GUI should only change the TLS setting when leaving the address input and only when explicit http:// or https:// is used.

**Comment by AnjaBruls** [comment]
Fixed since version v0.2.12.
