### ISSUE TITLE
Fixed address mode for ThingsGUI

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#86]
Read env variable like:

THINGSGUI_ADDRESS
THINGSGUI_AUTH_METHOD
THINGSGUI_SSL (optional)

When both the ADDRESS and AUTH_METHOD are configured, ThingsGUI should ask for the Token only and *not* use any local storage for token information etc.

We may then be able to host ThingsGUI for connecting to playground environments by using something like https://gui.playground.thingsdb.net

The next step could be an auto-login from the website so we may open the GUI directly from the thingsdb.net website.

**Comment by AnjaBruls** [comment]
Fixed since version v0.2.12.
