### ISSUE TITLE
Syntax highlighting for first, last, is_regex and regex functions

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#98]
See https://github.com/thingsdb/ThingsDB/issues/156, https://github.com/thingsdb/ThingsDB/issues/150  and  https://github.com/thingsdb/ThingsDB/issues/149

Functions:

- regex()
- is_regex()
- *list*.first()
- *list*.last()

**Comment by AnjaBruls** [comment]
Added in v0.3.0.
